language: node_js
node_js:
  - node
before_install:
  - npm install -g codecov
install:
  - yarn install --pure-lockfile
before_script:
  - yarn build
script:
  - yarn test
  - yarn coverage
  - codecov
  - yarn prettier
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then scripts/package-version.sh @toi/toi packages/toi; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then scripts/package-version.sh @toi/toix packages/toix; fi'
deploy:
  provider: script
  script:
    - bash scripts/deploy.sh
  on:
    branch: master
